ya_data_consumer:
    resource: "@YaDataConsumerBundle/Controller/"
    type:     annotation
    prefix:   /consumer

ya_api:
    resource: "@YaApiBundle/Controller/"
    type:     annotation
    prefix:   /

air_web_app:
    resource: "@AirWebAppBundle/Resources/config/routing.yml"
    prefix:   /

#ya_data_collector:
#    resource: "@YaDataCollectorBundle/Controller/"
#    type:     annotation
#    prefix:ctor

ya_core_model:
    resource: "@YaCoreModelBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc/api

byexample_demo_securityrest:
  resource: Ya\CoreModelBundle\Controller\SecurityController
  type: rest
  
resource_loc:
  resource: Ya\DataCollectorBundle\Controller\ResourceController
  type: rest

api_location:
  resource: Ya\CoreModelBundle\Controller\DefaultController
  prefix: /data
  type: annotation

fake_location:
  resource: Ya\DataCollectorBundle\Controller\DefaultController
  prefix: /collect
  type: annotation
