parameters:
#    air_web_app.example.class: Air\WebAppBundle\Example

services:
#    air_web_app.example:
#        class: %air_web_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
