ya_api_observation_get:
    pattern:  /api/observation
    defaults: { _controller: YaApiBundle:ObservationApi:getObservation }
    methods:  [GET]
    
ya_api_observation_post:
    pattern:  /api/observation
    defaults: { _controller: YaApiBundle:ObservationApi:postObservation }
    methods:  [POST]