parameters:
#    ya_core_model.example.class: Ya\CoreModelBundle\Example

services:
#    ya_core_model.example:
#        class: %ya_core_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
