<?php

namespace Ya\CoreModelBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AirQualityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirQualityCategoryRepository extends EntityRepository
{
  public function getByAqiValue($aqiValue)
  {
    $em = $this->getEntityManager();
    $query = $em->createQueryBuilder()
      ->select('aqc')
      ->from('Ya\CoreModelBundle\Entity\AirQualityCategory', 'aqc')
      ->where('aqc.min <= :aqiValue')
      ->andWhere('aqc.max >= :aqiValue')
      ->setParameter('aqiValue', $aqiValue);
    return $query->getQuery()->execute();
  }
}
