<?php

namespace Ya\CoreModelBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Acl\Domain\DoctrineAclCache;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends EntityRepository
{
  public function getById($id)
  {
    $em = $this->getEntityManager();
    $query = $em->createQueryBuilder()
      ->select('o')
      ->from('Ya\CoreModelBundle\Entity\Observation', 'o')
      ->where('o.id <= :id')
      ->setParameter('id', $id);
    return $query->getQuery()->setHydrationMode(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY)->execute();
  }

  public function getByQuadrant($lat1, $lon1, $lat2, $lon2)
  {
    $em = $this->getEntityManager();
    $query = $em->createQueryBuilder()
      ->select('o.aqiValue, ra.latitude, ra.longitude')
      ->from('Ya\CoreModelBundle\Entity\Observation', 'o')
      ->leftJoin('Ya\CoreModelBundle\Entity\ReportingArea', 'ra')
      ->where('ra.latitude >= :lat1 AND ra.latitude <= :lat2')
      ->andWhere('ra.longitude >= :lon1 AND ra.longitude <= :lon2')
      ->setParameter('lat1', $lat1)
      ->setParameter('lat2', $lat2)
      ->setParameter('lon1', $lon1)
      ->setParameter('lon2', $lon2);
    echo $query->getQuery()->getSQL();
    return $query->getQuery()->setHydrationMode(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY)->execute();
  }
}
