<?php

namespace Ya\CoreModelBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Acl\Domain\DoctrineAclCache;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends EntityRepository
{
  public function getById($id)
  {
    $em = $this->getEntityManager();
    $query = $em->createQueryBuilder()
      ->select('o')
      ->from('Ya\CoreModelBundle\Entity\Observation', 'o')
      ->where('o.id <= :id')
      ->setParameter('id', $id);
    return $query->getQuery()->setHydrationMode(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY)->execute();
  }
}
