parameters:
    collector.airnow.class: Ya\DataCollectorBundle\Services\AirNowService
    collector.fake.class: Ya\DataCollectorBundle\Services\FakeService
 
services:
    collector.fake:
        class: "%collector.fake.class%"
        arguments:
          em: @doctrine.orm.entity_manager
          kernel: @kernel